insultes:
  - "ez"
  - "fdp"
  - "connard"
  - "pute"
  - "putain"
  - "putains"
  - "nique ta mere"
  - "nique ta mère"
  - "fil de pute"
  - "fils de pute"
  - "salope"
  - "connasses"
  - "connasse"
  - "salopes"
  - "batard"
  - "batards"
  - "batar"
  - "rekt"
  - "merde"
  - "enculé"
  - "encule"
  - "ftg"
  - "guelle"
  - "salop"